"""
Merge generated_listings.json (from scrape_listings.py) with any Carousell
data from microsearch.py into src/data/listings.ts.

Usage:
  python scripts/apply_listings.py
"""

import json
import re
from datetime import date
from pathlib import Path

GENERATED = Path(__file__).parent.parent / "src" / "data" / "generated" / "generated_listings.json"
CAROUSELL_GENERATED = Path(__file__).parent.parent / "src" / "data" / "generated" / "carousell_listings.json"
OUTPUT_TS = Path(__file__).parent.parent / "src" / "data" / "listings.ts"

# Platforms supported by the Listing TypeScript interface
VALID_PLATFORMS = {"Carousell", "eBay", "Reddit", "Chrono24", "Other"}


def esc(s: str) -> str:
    return s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', ' ')


def listing_to_ts(item: dict, idx: int) -> str:
    platform = item.get("platform", "Other")
    if platform not in VALID_PLATFORMS:
        platform = "Other"
    condition = item.get("condition", "Good")
    if condition not in ("New", "Like New", "Good", "Fair"):
        condition = "Good"
    price = item.get("price", 0)
    price_val = int(price) if isinstance(price, float) and price == int(price) else price
    image = item.get("imageUrl", "")
    image_line = f"\n    imageUrl: '{esc(image)}'," if image else ""

    return (
        f"  {{\n"
        f"    id: '{idx}',\n"
        f"    brand: {json.dumps(item.get('brand', ''))},\n"
        f"    title: {json.dumps(item.get('title', ''))},\n"
        f"    price: {price_val},\n"
        f"    currency: '{item.get('currency', 'USD')}',\n"
        f"    condition: '{condition}',\n"
        f"    platform: '{platform}',\n"
        f"    location: '{esc(item.get('location', 'Unknown'))}',\n"
        f"    url: {json.dumps(item.get('url', ''))},\n"
        f"    postedAt: '{item.get('postedAt', date.today().isoformat())}',{image_line}\n"
        f"  }},"
    )


def main():
    all_items = []

    # Load multi-platform scraped listings
    if GENERATED.exists():
        with open(GENERATED, encoding='utf-8') as f:
            scraped = json.load(f)
        all_items.extend(scraped)
        print(f"Loaded {len(scraped)} listings from generated_listings.json")
    else:
        print("No generated_listings.json found — run scrape_listings.py first")

    # Load Carousell listings if they exist separately
    if CAROUSELL_GENERATED.exists():
        with open(CAROUSELL_GENERATED, encoding='utf-8') as f:
            carousell = json.load(f)
        all_items.extend(carousell)
        print(f"Loaded {len(carousell)} Carousell listings")

    if not all_items:
        print("No listings data found. Exiting.")
        return

    # Deduplicate by URL
    seen_urls = set()
    deduped = []
    for item in all_items:
        url = item.get("url", "")
        if url and url not in seen_urls:
            seen_urls.add(url)
            deduped.append(item)

    # Sort: live first, then by date descending
    def sort_key(x):
        status_order = {"live": 0, "upcoming": 1, "sold_out": 2}
        return (status_order.get(x.get("status", "live"), 0),
                x.get("postedAt", "0000"))

    deduped.sort(key=sort_key, reverse=False)

    # Filter out zero-price items and invalid entries
    deduped = [x for x in deduped if x.get("price", 0) > 0 and x.get("title")]

    # Cap at 200 listings
    deduped = deduped[:200]

    ts_lines = [
        "// AUTO-GENERATED by scripts/apply_listings.py — do not edit manually",
        f"// Last updated: {date.today().isoformat()}",
        f"// Sources: {', '.join(sorted(set(x.get('platform','?') for x in deduped)))}",
        "",
        "export interface Listing {",
        "  id: string",
        "  brand: string",
        "  title: string",
        "  price: number",
        "  currency: string",
        "  condition: 'New' | 'Like New' | 'Good' | 'Fair'",
        "  platform: 'Carousell' | 'eBay' | 'Reddit' | 'Chrono24' | 'Other'",
        "  location: string",
        "  url: string",
        "  postedAt: string",
        "  imageUrl?: string",
        "}",
        "",
        "export const listings: Listing[] = [",
    ]

    for i, item in enumerate(deduped):
        ts_lines.append(listing_to_ts(item, i + 1))

    ts_lines += [
        "]",
        "",
        "export const listingBrands = [...new Set(listings.map(l => l.brand))].sort()",
        "export const listingPlatforms = [...new Set(listings.map(l => l.platform))].sort()",
        "export const listingLocations = [...new Set(listings.map(l => l.location))].sort()",
        "export const listingConditions = ['New', 'Like New', 'Good', 'Fair'] as const",
        "",
    ]

    OUTPUT_TS.write_text('\n'.join(ts_lines), encoding='utf-8')
    print(f"\nWrote {len(deduped)} listings to listings.ts")

    # Platform breakdown
    from collections import Counter
    counts = Counter(x.get("platform", "?") for x in deduped)
    for platform, count in sorted(counts.items()):
        print(f"  {platform:<12} {count}")


if __name__ == "__main__":
    main()
