"""
Apply DeepSeek-generated brand content to brands.ts and brand page metadata.

This reads src/data/generated/brand_content.json and updates:
1. Brand descriptions in brands.ts
2. Generates src/data/brand_seo.ts with SEO titles/descriptions for each brand page

Usage:
  python scripts/apply_brand_content.py
"""

import json
import re
import sys
from pathlib import Path

GENERATED = Path(__file__).parent.parent / "src" / "data" / "generated" / "brand_content.json"
BRANDS_TS = Path(__file__).parent.parent / "src" / "data" / "brands.ts"
SEO_TS    = Path(__file__).parent.parent / "src" / "data" / "brand_seo.ts"

def slug(name: str) -> str:
    return re.sub(r'[^a-z0-9]+', '-', name.lower()).strip('-')

def main():
    if not GENERATED.exists():
        print("No generated content found. Run: python scripts/generate_content.py --mode brands")
        sys.exit(1)

    content = json.loads(GENERATED.read_text(encoding='utf-8-sig', errors='replace'))
    print(f"Loaded content for {len(content)} brands")

    # --- 1. Update brand descriptions in brands.ts ---
    brands_src = BRANDS_TS.read_text(encoding='utf-8')
    updated = 0

    for brand_name, data in content.items():
        new_desc = data.get("brand_description", "").replace('"', '\\"').replace('\n', ' ').strip()
        if not new_desc:
            continue

        # Match: description: 'old text' or description: "old text"
        pattern = rf"(name:\s*['\"]){re.escape(brand_name)}(['\"].*?description:\s*['\"])([^'\"]+)(['\"])"

        def replacer(m):
            return f"{m.group(1)}{brand_name}{m.group(2)}{new_desc}{m.group(4)}"

        new_src, n = re.subn(pattern, replacer, brands_src, count=1, flags=re.DOTALL)
        if n:
            brands_src = new_src
            updated += 1

    BRANDS_TS.write_text(brands_src, encoding='utf-8')
    print(f"Updated {updated} brand descriptions in brands.ts")

    # --- 2. Generate brand_seo.ts ---
    lines = [
        "// AUTO-GENERATED by scripts/apply_brand_content.py — do not edit manually",
        "export interface BrandSEO {",
        "  seoTitle: string",
        "  seoDescription: string",
        "  whyBuy: string[]",
        "  keyCollection: string",
        "}",
        "",
        "export const brandSEO: Record<string, BrandSEO> = {",
    ]

    for brand_name, data in content.items():
        s = slug(brand_name)
        seo_title = data.get("seo_title", f"{brand_name} Watches").replace("'", "\\'")
        seo_desc  = data.get("seo_description", "").replace("'", "\\'")
        key_col   = data.get("key_collection", "").replace("'", "\\'").replace('\n', ' ')
        why_buy   = data.get("why_buy", [])
        why_json  = json.dumps(why_buy, ensure_ascii=False)

        lines.append(f"  '{s}': {{")
        lines.append(f"    seoTitle: {json.dumps(seo_title)},")
        lines.append(f"    seoDescription: {json.dumps(seo_desc)},")
        lines.append(f"    whyBuy: {why_json},")
        lines.append(f"    keyCollection: {json.dumps(key_col)},")
        lines.append(f"  }},")

    lines.append("}")
    lines.append("")

    SEO_TS.write_text('\n'.join(lines), encoding='utf-8')
    print(f"Generated {SEO_TS}")

if __name__ == '__main__':
    main()
